### ISSUE TITLE
Ticket voted is different of spendable

### ISSUE THREAD

**Issue by rodrigondec** [dcrbrdev/JackBot#46]
as 99split said
> new blocks take 256 confirmations to mature and become spendable. all rewards, ticket and pow mining alike, need to wait 256 blocks after mined.

It will be interesting to have a expandable status after the voted status.

The ticket already has `vote_id` after it gets voted. Now its needed to calculate (?) the remaining blocks it have before is spendable

**Comment by fguisso** [comment]
get the vote's block height and comparing to the best block/actual block height
